import { Inter } from 'next/font/google'
import './globals.css'
import "@fortawesome/fontawesome-svg-core"
import {config} from "@fortawesome/fontawesome-svg-core"
import Nav from "@/app/component/Nav"
config.autoAddCss=false;


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'home',
  description: 'Generated by create next app',
  
}

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
    
      <body className={inter.className}>
        <Nav/>
        {children}
     
      </body>

      
    </html>
  )
}
